[dataloader]
baseUrl = "https://data.sfgov.org/resource/wwmu-gmzc.json"
batchSize = 1000

[db]
host = "localhost:27017"
dbName = "sf-movie-locations"
collectionName = "movies"
username = "dataloader"
password = "qwerty23"
timeout = 60